In [2]:
import gym
import highway_env
from envs.pomdp_wrapper import POMDPWrapper

import warnings
warnings.simplefilter("ignore")

In [9]:
import numpy as np

env = POMDPWrapper("racetrack-v0", 'flickering')
env.configure({
    "observation": {
        "type": "Kinematics",
        "vehicles_count": 15,
        "features": ["presence", "x", "y", "vx", "vy", "cos_h", "sin_h"],
        "features_range": {
            "x": [-100, 100],
            "y": [-100, 100],
            "vx": [-20, 20],
            "vy": [-20, 20]
        },
        "grid_size": [[-27.5, 27.5], [-27.5, 27.5]],
        "grid_step": [5, 5],
        "absolute": False
    }
    # ,
    # "action": {
    #     "type": "ContinuousAction"
    # }
})

print(np.prod(env.observation_space.shape))

288


In [ ]:
[false true [false false false false false]
[  0     1   [ 2     3     4]




In [1]:
env.observation_space.shape

NameError: name 'env' is not defined

In [2]:
env = POMDPWrapper("racetrack-v0", 'flickering')
env.configure({
    "observation": {
        "type": "Kinematics",
        "vehicles_count": 15,
        "features": ["presence", "x", "y", "vx", "vy", "cos_h", "sin_h"],
        "features_range": {
            "x": [-100, 100],
            "y": [-100, 100],
            "vx": [-20, 20],
            "vy": [-20, 20]
        },
        "grid_size": [[-27.5, 27.5], [-27.5, 27.5]],
        "grid_step": [5, 5],
        "absolute": False
    }
    # ,
    # "action": {
    #     "type": "ContinuousAction"
    # }
})

env.reset()

for _ in range(6):
    action = env.action_space.sample()
   # action = env.action_type.actions_indexes["IDLE"]
    obs, reward, done, info = env.step(action)
    # print(obs)
    env.render()
env.close()


In [3]:
env = POMDPWrapper("racetrack-v0", 'flickering')
action = env.action_space.sample()
print(action.shape)

(1,)


In [3]:
vars(env.action_space)

NameError: name 'env' is not defined

In [1]:
import numpy as np
ind = np.random.randint(5, 2000, size=12)
print(ind)

[  79  391 1695  532  299  244  682 1426 1307 1325  173 1742]


In [5]:
import numpy as np
from replay import ReplayBuffer


buffer = ReplayBuffer(1, 1, 100)

for i in range(101):
    mul = np.ones(1)*i
    mul2 = mul + 1
    rand = np.random.random(1)
    buffer.push(mul, mul, mul2, rand, mul)

print(buffer.size)

# Not tested for dones

okay = buffer.prior_samples(10, 5)

print(okay[1])

100
[[[51.]
  [52.]
  [53.]
  [54.]
  [55.]]

 [[ 4.]
  [ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[29.]
  [30.]
  [31.]
  [32.]
  [33.]]

 [[77.]
  [78.]
  [79.]
  [80.]
  [81.]]

 [[23.]
  [24.]
  [25.]
  [26.]
  [27.]]

 [[17.]
  [18.]
  [19.]
  [20.]
  [21.]]

 [[48.]
  [49.]
  [50.]
  [51.]
  [52.]]

 [[86.]
  [87.]
  [88.]
  [89.]
  [90.]]

 [[86.]
  [87.]
  [88.]
  [89.]
  [90.]]

 [[29.]
  [30.]
  [31.]
  [32.]
  [33.]]]


In [7]:
import numpy as np

def test(id, his_len, done):
    start_id = id-his_len
        
    not_valid = True
    while not_valid:

        print(f'At while {start_id}, {id}')

        # Check sequence for termination
        print(done[start_id:id] == 1.0)
        if len(np.where(done[start_id:id] == 1)[0]) != 0:
            print(f'Invalid hist sequence with id {id}, and done {(done[start_id:id] == 1)}')
            temp = start_id + (np.where(done[start_id:id] == 1)[0][-1]) + 1
            if (temp + his_len) >= len(done):
                print(f'length of done {len(done)}; {temp + his_len}')
                start_id = np.random.randint(0, len(x)-his_len,1)[0]
            else:
                start_id = temp
            id = start_id + his_len
        
        if (len(np.where(done[start_id:id] == 1)[0]) == 0):
            not_valid = False
    
    return start_id, id

x = np.array([0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0])
his_len = 5
id = np.random.randint(his_len, len(x),1)[0]
print(f'True at {np.where(x==1)}, random id {id}')
start_id, id = test(id, his_len, x)

print(f'start at {start_id}, id {id}')
print(x[start_id:id])